trigger:
- master

resources:
- repo: self

pool:
  vmImage: ubuntu-latest

steps:
- task: TerraformTaskV1@0
  displayName: terraform validate
  inputs:
    provider: azurerm
    command: validate
    workingDirectory: $(agent.builddirectory)

- task: ArchiveFiles@2
  displayName: archive
  inputs:
    rootFolderOrFile: $(agent.builddirectory)
    includeRootFolder: false
    archiveType: zip
    archiveFile: $(build.artifactstagingdirectory)/iac-$(build.buildid).zip
    replaceExistingArchive: true

- task: PublishBuildArtifacts@1
  displayName: publish
  inputs:
    pathtoPublish: $(build.artifactstagingdirectory)
    artifactName: iac
    publishLocation: Container
