trigger:
- master

resources:
- repo: self

pool:
  vmImage: ubuntu-latest

steps:
- task: TerraformTaskV1@0
  displayName: terraform validate
  inputs:
    provider: azurerm
    command: validate
    workingDirectory: $(agent.builddirectory)
    
- task: Bash@3
  inputs:
    targetType: 'inline'
    script: 'ls'

- task: TerraformTaskV1@0
  displayName: terraform validate github
  inputs:
    provider: github
    command: validate
    workingDirectory: $(agent.builddirectory)/github

- task: CopyFiles@2
  displayName: copy files
  inputs:
    sourceFolder: $(agent.builddirectory)
    contents: '**'
    targetFolder: $(build.artifactstagingdirectory)

- task: PublishBuildArtifacts@1
  displayName: publish
  inputs:
    pathtoPublish: $(build.artifactstagingdirectory)
    artifactName: iac
    publishLocation: Container
